# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0002_snowcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=20)),
            ],
        ),
    ]
