# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0003_userinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinput',
            name='loc',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
