# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0008_auto_20180419_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='loc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='num',
            field=models.CharField(default='', max_length=20),
        ),
    ]
